### ISSUE TITLE
batch editor 1.0 with eclipse oxygen2 cause Eclipse no response

### ISSUE THREAD

**Issue by woniulive** [de-jcup/eclipse-batch-editor#12]
In Eclipse Oxygen2，when editing bat file with batch editor,Eclipse always become no response.when i input ech,it is OK.but when i continue type o,it become no response.however,if i input ech,then type blank space, type o,if i delete blank type now.it is OK.
Os:win10 professional x64
JAVA version:1.8_152
eclipse platform:eclipse c++ x64

**Comment by de-jcup** [comment]
Got same problem with 
- Linux
- Eclipse Oxygen2

Steps to reproduce:
- create an empty batch file (e.g. "test-empty.bat")
- open the file with batch editor
- type "echo"
- eclipse frezes complete!

**Comment by de-jcup** [comment]
The same problem exists when running bash editor inside a 
Eclipse NEON.3 PDE environment.

**Comment by de-jcup** [comment]
@woniulive I just deployed the version 1.0.1 to eclipse marketplace which contains the bugfix. There is no longer an infinite loop.
Thanks for reporting the bug.

**Comment by woniulive** [comment]
Thankyou,I will download after a while.:grinning::grinning:
