### ISSUE TITLE
Feature Request: Custom syntax coloring for labels and numbers

### ISSUE THREAD

**Issue by Mito173** [de-jcup/eclipse-batch-editor#17]
First of all, thanks for this great editor - finally I can edit windows batch files inside eclipse and don't need to use an external editor!
I have to work with labels and return codes from called programs a lot. For this, it would be great if there were a configuration items in Syntax Coloring for labels (including the ':'-character) and numbers.

I thought I just five it a try and create a corresponding feature request for your project :-)

Kind regards,
Michael

By the way, your SQL-Editor also works great!

**Comment by Mito173** [comment]
Well, after writing this feature request I realized that the last commit was some years ago already. So in case this project is discontinued, would you please give me some hints at least where in the code I would add this? It is some time ago that I worked with Java but I assume it will not be a big change so I may give it a try.

**Comment by de-jcup** [comment]
Sorry for the late response... I was extreme busy this year.
The project is not discontinued, but there were just no additional feature requests (it just worked...).

At the moment you can setup following colors:
![image](https://user-images.githubusercontent.com/11644753/102690816-58af7f00-4208-11eb-9699-43e3f4566d00.png)

So as far as I understand you would like to
1. have labels shown up in a separate color + customizable in preferences
2. every number should have also a separate color + customizable in preferences

I think this should be not much effort and is good enhancement. Will be implemented.

**Comment by de-jcup** [comment]
Labels + Numbers are now highlighted:

![image](https://user-images.githubusercontent.com/11644753/102699914-f32fb280-4248-11eb-9750-6f90d5c7b16c.png)

![image](https://user-images.githubusercontent.com/11644753/102699854-874d4a00-4248-11eb-8612-6e7a87510cc6.png)

**Comment by de-jcup** [comment]
Labels and Numbers got dedicated color settings in preferences:
![image](https://user-images.githubusercontent.com/11644753/102699963-5de0ee00-4249-11eb-9056-1d04d7c8f484.png)

**Comment by de-jcup** [comment]
@Mito173 : Version 1.1.0 contains the new feature and is now released on eclipse marketplace

**Comment by de-jcup** [comment]
@Mito173 : I will try to fix mentioned problem in #24 in next version

**Comment by de-jcup** [comment]
@Mito173 : 1.1.1 released on marketplace - digits now rendered correctly.
