### ISSUE TITLE
Variables with marked for delayed expansion not recognized

### ISSUE THREAD

**Issue by TheGypsyCoder** [de-jcup/eclipse-batch-editor#18]
When a variable is referenced as !VarName! so that the variable is expanded at execution time for delayed evnvironment variable expansion, the !VarName! is not syntax colored as %VarName% is.

Thanks for a great addition to Eclipse for when I need to delve into the batch file realm.

**Comment by de-jcup** [comment]
Link to syntax: https://ss64.com/nt/delayedexpansion.html

Link to some examples: https://stackoverflow.com/a/10558905/2590615

**Comment by de-jcup** [comment]
Works now as suggested:

![image](https://user-images.githubusercontent.com/11644753/102694503-bac8ae00-4221-11eb-866b-190f2d7c99eb.png)

**Comment by de-jcup** [comment]
@TheGypsyCoder : Version 1.1.0 contains the improvement and is now released on eclipse marketplace

**Comment by TheGypsyCoder** [comment]
Installed and tested, works as advertised.

Thanks again for writing this editor plugin for eclipse, .bat files will be with us for a long time to time.
