### ISSUE TITLE
Support/associate with .cmd extention

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-batch-editor#9]
Windows also can execute scripts with `.cmd` extention

https://stackoverflow.com/questions/148968/windows-batch-files-bat-vs-cmd

---
Not to mention PowerShell https://en.wikipedia.org/wiki/PowerShell

**Comment by de-jcup** [comment]
- [x] extend plugin.xml to link "cmd" to editor as well
- [x] add fileextension to eclipse marketplace
- [x] add information "(.bat, .cmd)" instead of "(.bat)"
- [x] update README.md in code
